name: mlproject-env
dependencies:
  - python=3.9
  - pip
  - pip:
      - mlflow==2.19.0
      - scikit-learn
      - pandas
      - numpy
      - joblib
      - matplotlib
      - seaborn
      - dagshub